page 20260
/bbs/Gossiping/M.1495088667.A.95B.html download to ptt/Gossiping/20260_0.txt, time: 5.610000
/bbs/Gossiping/M.1495088681.A.D4E.html download to ptt/Gossiping/20260_1.txt, time: 3.530000
/bbs/Gossiping/M.1495088731.A.409.html download to ptt/Gossiping/20260_2.txt, time: 5.380000
/bbs/Gossiping/M.1495088768.A.706.html download to ptt/Gossiping/20260_3.txt, time: 4.680000
/bbs/Gossiping/M.1495088793.A.5A5.html download to ptt/Gossiping/20260_4.txt, time: 6.820000
/bbs/Gossiping/M.1495088795.A.21D.html download to ptt/Gossiping/20260_5.txt, time: 5.750000
/bbs/Gossiping/M.1495088883.A.47F.html download to ptt/Gossiping/20260_6.txt, time: 4.460000
/bbs/Gossiping/M.1495088922.A.181.html download to ptt/Gossiping/20260_7.txt, time: 4.440000
/bbs/Gossiping/M.1495088930.A.D36.html download to ptt/Gossiping/20260_8.txt, time: 6.830000
/bbs/Gossiping/M.1495089026.A.6A9.html download to ptt/Gossiping/20260_9.txt, time: 5.090000
/bbs/Gossiping/M.1495089056.A.F37.html download to ptt/Gossiping/20260_10.txt, time: 4.290000
/bbs/Gossiping/M.1495089074.A.12C.html download to ptt/Gossiping/20260_11.txt, time: 5.720000
/bbs/Gossiping/M.1495089097.A.833.html download to ptt/Gossiping/20260_12.txt, time: 4.190000
/bbs/Gossiping/M.1495089124.A.AF0.html download to ptt/Gossiping/20260_13.txt, time: 3.450000
/bbs/Gossiping/M.1495089130.A.099.html download to ptt/Gossiping/20260_14.txt, time: 3.310000
/bbs/Gossiping/M.1495089143.A.BE5.html download to ptt/Gossiping/20260_15.txt, time: 5.010000
/bbs/Gossiping/M.1495089171.A.043.html download to ptt/Gossiping/20260_16.txt, time: 5.260000
/bbs/Gossiping/M.1495089219.A.B7F.html download to ptt/Gossiping/20260_17.txt, time: 4.260000
/bbs/Gossiping/M.1495089232.A.E84.html download to ptt/Gossiping/20260_18.txt, time: 5.190000
/bbs/Gossiping/M.1495089253.A.006.html download to ptt/Gossiping/20260_19.txt, time: 4.060000
page 20259
/bbs/Gossiping/M.1495088143.A.ECA.html download to ptt/Gossiping/20259_0.txt, time: 5.100000
/bbs/Gossiping/M.1495088160.A.431.html download to ptt/Gossiping/20259_1.txt, time: 5.740000
/bbs/Gossiping/M.1495088160.A.066.html download to ptt/Gossiping/20259_2.txt, time: 4.620000
/bbs/Gossiping/M.1495088173.A.221.html download to ptt/Gossiping/20259_3.txt, time: 4.490000
/bbs/Gossiping/M.1495088176.A.7BD.html download to ptt/Gossiping/20259_4.txt, time: 3.920000
/bbs/Gossiping/M.1495088234.A.12E.html download to ptt/Gossiping/20259_5.txt, time: 6.920000
/bbs/Gossiping/M.1495088282.A.E97.html download to ptt/Gossiping/20259_6.txt, time: 5.680000
/bbs/Gossiping/M.1495088295.A.983.html download to ptt/Gossiping/20259_7.txt, time: 4.830000
/bbs/Gossiping/M.1495088346.A.C8E.html download to ptt/Gossiping/20259_8.txt, time: 3.940000
/bbs/Gossiping/M.1495088368.A.190.html download to ptt/Gossiping/20259_9.txt, time: 6.980000
/bbs/Gossiping/M.1495088413.A.E2C.html download to ptt/Gossiping/20259_10.txt, time: 4.890000
/bbs/Gossiping/M.1495088424.A.702.html download to ptt/Gossiping/20259_11.txt, time: 7.350000
/bbs/Gossiping/M.1495088438.A.D57.html download to ptt/Gossiping/20259_12.txt, time: 7.490000
/bbs/Gossiping/M.1495088458.A.C71.html download to ptt/Gossiping/20259_13.txt, time: 5.900000
/bbs/Gossiping/M.1495088463.A.7AD.html download to ptt/Gossiping/20259_14.txt, time: 3.150000
/bbs/Gossiping/M.1495088466.A.09A.html download to ptt/Gossiping/20259_15.txt, time: 6.070000
/bbs/Gossiping/M.1495088521.A.579.html download to ptt/Gossiping/20259_16.txt, time: 4.650000
/bbs/Gossiping/M.1495088536.A.939.html download to ptt/Gossiping/20259_17.txt, time: 7.730000
/bbs/Gossiping/M.1495088555.A.CA1.html download to ptt/Gossiping/20259_18.txt, time: 12.250000
/bbs/Gossiping/M.1495088638.A.8C0.html download to ptt/Gossiping/20259_19.txt, time: 16.490000
page 20258
/bbs/Gossiping/M.1495087567.A.54A.html download to ptt/Gossiping/20258_0.txt, time: 5.180000
/bbs/Gossiping/M.1495087568.A.4EF.html download to ptt/Gossiping/20258_1.txt, time: 6.120000
/bbs/Gossiping/M.1495087595.A.81A.html download to ptt/Gossiping/20258_2.txt, time: 6.260000
/bbs/Gossiping/M.1495087624.A.A12.htmlTraceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crawler.py", line 177, in <module>
    main(sys.argv[1:])
  File "./crawler.py", line 158, in main
    downloadForum(forumName, startPage, pages)
  File "./crawler.py", line 140, in downloadForum
    downloadPage(str(articleCount), forumName, pageNum, 'https://www.ptt.cc'+link)
  File "./crawler.py", line 82, in downloadPage
    pageText = getPageText(link)
  File "./crawler.py", line 13, in getPageText
    pageText=requests.get(link, cookies={'over18':'1'}).text
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
