page 20580
/bbs/Gossiping/M.1495295827.A.339.html download to ptt/Gossiping/20580_0.txt, time: 4.560000
/bbs/Gossiping/M.1495295843.A.A89.html download to ptt/Gossiping/20580_1.txt, time: 7.720000
/bbs/Gossiping/M.1495295923.A.E5B.html download to ptt/Gossiping/20580_2.txt, time: 4.590000
/bbs/Gossiping/M.1495295924.A.C93.html download to ptt/Gossiping/20580_3.txt, time: 3.030000
/bbs/Gossiping/M.1495295933.A.451.html download to ptt/Gossiping/20580_4.txt, time: 3.510000
/bbs/Gossiping/M.1495295959.A.9B2.html download to ptt/Gossiping/20580_5.txt, time: 4.490000
/bbs/Gossiping/M.1495296014.A.C98.html download to ptt/Gossiping/20580_6.txt, time: 4.630000
/bbs/Gossiping/M.1495296046.A.8D4.html download to ptt/Gossiping/20580_7.txt, time: 4.390000
/bbs/Gossiping/M.1495296051.A.FE5.html download to ptt/Gossiping/20580_8.txt, time: 7.290000
/bbs/Gossiping/M.1495296098.A.636.html download to ptt/Gossiping/20580_9.txt, time: 5.740000
/bbs/Gossiping/M.1495296125.A.CD6.html download to ptt/Gossiping/20580_10.txt, time: 4.400000
/bbs/Gossiping/M.1495296131.A.61D.html download to ptt/Gossiping/20580_11.txt, time: 5.150000
/bbs/Gossiping/M.1495296154.A.B31.html download to ptt/Gossiping/20580_12.txt, time: 2.980000
/bbs/Gossiping/M.1495296157.A.AB4.html download to ptt/Gossiping/20580_13.txt, time: 4.140000
/bbs/Gossiping/M.1495296169.A.67B.html download to ptt/Gossiping/20580_14.txt, time: 5.860000
/bbs/Gossiping/M.1495296209.A.7F0.html download to ptt/Gossiping/20580_15.txt, time: 3.920000
/bbs/Gossiping/M.1495296261.A.D28.html download to ptt/Gossiping/20580_16.txt, time: 3.970000
/bbs/Gossiping/M.1495296262.A.4FC.html download to ptt/Gossiping/20580_17.txt, time: 5.940000
/bbs/Gossiping/M.1495296271.A.ACA.html download to ptt/Gossiping/20580_18.txt, time: 4.260000
/bbs/Gossiping/M.1495296298.A.29D.html download to ptt/Gossiping/20580_19.txt, time: 5.190000
page 20579
/bbs/Gossiping/M.1495295397.A.DCB.html download to ptt/Gossiping/20579_0.txt, time: 6.630000
/bbs/Gossiping/M.1495295455.A.EB4.html download to ptt/Gossiping/20579_1.txt, time: 4.770000
/bbs/Gossiping/M.1495295455.A.E13.html download to ptt/Gossiping/20579_2.txt, time: 5.590000
/bbs/Gossiping/M.1495295480.A.E0A.html download to ptt/Gossiping/20579_3.txt, time: 5.470000
/bbs/Gossiping/M.1495295563.A.713.html download to ptt/Gossiping/20579_4.txt, time: 4.310000
/bbs/Gossiping/M.1495295590.A.FA1.html download to ptt/Gossiping/20579_5.txt, time: 4.630000
/bbs/Gossiping/M.1495295642.A.6B9.html download to ptt/Gossiping/20579_6.txt, time: 4.390000
/bbs/Gossiping/M.1495295645.A.2FE.html download to ptt/Gossiping/20579_7.txt, time: 6.500000
/bbs/Gossiping/M.1495295653.A.06B.html download to ptt/Gossiping/20579_8.txt, time: 4.220000
/bbs/Gossiping/M.1495295671.A.627.html download to ptt/Gossiping/20579_9.txt, time: 5.240000
/bbs/Gossiping/M.1495295683.A.390.html download to ptt/Gossiping/20579_10.txt, time: 4.560000
/bbs/Gossiping/M.1495295711.A.A19.html download to ptt/Gossiping/20579_11.txt, time: 5.430000
/bbs/Gossiping/M.1495295729.A.826.html download to ptt/Gossiping/20579_12.txt, time: 4.060000
/bbs/Gossiping/M.1495295751.A.DED.html download to ptt/Gossiping/20579_13.txt, time: 5.090000
/bbs/Gossiping/M.1495295752.A.E3A.html download to ptt/Gossiping/20579_14.txt, time: 5.250000
/bbs/Gossiping/M.1495295753.A.2EF.html download to ptt/Gossiping/20579_15.txt, time: 4.530000
/bbs/Gossiping/M.1495295763.A.175.html download to ptt/Gossiping/20579_16.txt, time: 7.030000
/bbs/Gossiping/M.1495295779.A.D18.htmlTraceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crawler.py", line 177, in <module>
    main(sys.argv[1:])
  File "./crawler.py", line 158, in main
    downloadForum(forumName, startPage, pages)
  File "./crawler.py", line 140, in downloadForum
    downloadPage(str(articleCount), forumName, pageNum, 'https://www.ptt.cc'+link)
  File "./crawler.py", line 82, in downloadPage
    pageText = getPageText(link)
  File "./crawler.py", line 13, in getPageText
    pageText=requests.get(link, cookies={'over18':'1'}).text
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
