page 20770
/bbs/Gossiping/M.1495454581.A.213.html download to ptt/Gossiping/20770_0.txt, time: 5.350000
/bbs/Gossiping/M.1495454581.A.071.html download to ptt/Gossiping/20770_1.txt, time: 10.090000
/bbs/Gossiping/M.1495454597.A.E5A.html download to ptt/Gossiping/20770_2.txt, time: 4.050000
/bbs/Gossiping/M.1495454606.A.C6F.html download to ptt/Gossiping/20770_3.txt, time: 5.030000
/bbs/Gossiping/M.1495454665.A.61C.html download to ptt/Gossiping/20770_4.txt, time: 3.380000
/bbs/Gossiping/M.1495454698.A.F7A.html download to ptt/Gossiping/20770_5.txt, time: 4.460000
/bbs/Gossiping/M.1495454725.A.6AD.html download to ptt/Gossiping/20770_6.txt, time: 3.990000
/bbs/Gossiping/M.1495454726.A.B3E.html download to ptt/Gossiping/20770_7.txt, time: 5.930000
/bbs/Gossiping/M.1495454769.A.423.html download to ptt/Gossiping/20770_8.txt, time: 7.350000
/bbs/Gossiping/M.1495454776.A.68B.html download to ptt/Gossiping/20770_9.txt, time: 4.220000
/bbs/Gossiping/M.1495454858.A.E1A.html download to ptt/Gossiping/20770_10.txt, time: 4.480000
/bbs/Gossiping/M.1495454885.A.961.html download to ptt/Gossiping/20770_11.txt, time: 4.130000
/bbs/Gossiping/M.1495454902.A.390.html download to ptt/Gossiping/20770_12.txt, time: 6.100000
/bbs/Gossiping/M.1495454930.A.9B1.html download to ptt/Gossiping/20770_13.txt, time: 4.640000
/bbs/Gossiping/M.1495454952.A.661.html download to ptt/Gossiping/20770_14.txt, time: 5.520000
/bbs/Gossiping/M.1495454963.A.B26.html download to ptt/Gossiping/20770_15.txt, time: 5.180000
/bbs/Gossiping/M.1495454965.A.ED3.html download to ptt/Gossiping/20770_16.txt, time: 5.610000
/bbs/Gossiping/M.1495454986.A.18B.html download to ptt/Gossiping/20770_17.txt, time: 7.210000
/bbs/Gossiping/M.1495454991.A.CB2.html download to ptt/Gossiping/20770_18.txt, time: 5.900000
/bbs/Gossiping/M.1495455053.A.17C.html download to ptt/Gossiping/20770_19.txt, time: 4.700000
page 20769
/bbs/Gossiping/M.1495454046.A.4E2.html download to ptt/Gossiping/20769_0.txt, time: 7.120000
/bbs/Gossiping/M.1495454057.A.3F6.html download to ptt/Gossiping/20769_1.txt, time: 7.700000
/bbs/Gossiping/M.1495454063.A.F26.html download to ptt/Gossiping/20769_2.txt, time: 5.140000
/bbs/Gossiping/M.1495454064.A.6AE.html download to ptt/Gossiping/20769_3.txt, time: 4.920000
/bbs/Gossiping/M.1495454069.A.78B.html download to ptt/Gossiping/20769_4.txt, time: 4.550000
/bbs/Gossiping/M.1495454078.A.4A9.html download to ptt/Gossiping/20769_5.txt, time: 4.940000
/bbs/Gossiping/M.1495454109.A.A08.html download to ptt/Gossiping/20769_6.txt, time: 4.970000
/bbs/Gossiping/M.1495454140.A.B29.html download to ptt/Gossiping/20769_7.txt, time: 5.210000
/bbs/Gossiping/M.1495454144.A.5AC.html download to ptt/Gossiping/20769_8.txt, time: 4.980000
/bbs/Gossiping/M.1495454156.A.60C.html download to ptt/Gossiping/20769_9.txt, time: 5.130000
/bbs/Gossiping/M.1495454165.A.079.html download to ptt/Gossiping/20769_10.txt, time: 4.950000
/bbs/Gossiping/M.1495454309.A.E9C.html download to ptt/Gossiping/20769_11.txt, time: 5.570000
/bbs/Gossiping/M.1495454403.A.695.html download to ptt/Gossiping/20769_12.txt, time: 4.890000
/bbs/Gossiping/M.1495454437.A.4A4.html download to ptt/Gossiping/20769_13.txt, time: 3.840000
/bbs/Gossiping/M.1495454444.A.575.html download to ptt/Gossiping/20769_14.txt, time: 5.350000
/bbs/Gossiping/M.1495454506.A.5B0.html download to ptt/Gossiping/20769_15.txt, time: 8.840000
/bbs/Gossiping/M.1495454511.A.154.html download to ptt/Gossiping/20769_16.txt, time: 8.070000
/bbs/Gossiping/M.1495454528.A.F6D.htmlTraceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crawler.py", line 177, in <module>
    main(sys.argv[1:])
  File "./crawler.py", line 158, in main
    downloadForum(forumName, startPage, pages)
  File "./crawler.py", line 140, in downloadForum
    downloadPage(str(articleCount), forumName, pageNum, 'https://www.ptt.cc'+link)
  File "./crawler.py", line 82, in downloadPage
    pageText = getPageText(link)
  File "./crawler.py", line 13, in getPageText
    pageText=requests.get(link, cookies={'over18':'1'}).text
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
