page 21090
/bbs/Gossiping/M.1495645757.A.1BE.html download to ptt/Gossiping/21090_0.txt, time: 5.270000
/bbs/Gossiping/M.1495645762.A.B5A.html download to ptt/Gossiping/21090_1.txt, time: 4.870000
/bbs/Gossiping/M.1495645793.A.833.html download to ptt/Gossiping/21090_2.txt, time: 4.630000
/bbs/Gossiping/M.1495645832.A.3C2.html download to ptt/Gossiping/21090_3.txt, time: 7.900000
/bbs/Gossiping/M.1495645865.A.24D.html download to ptt/Gossiping/21090_4.txt, time: 5.150000
/bbs/Gossiping/M.1495645888.A.3A3.html download to ptt/Gossiping/21090_5.txt, time: 5.790000
/bbs/Gossiping/M.1495645915.A.D95.html download to ptt/Gossiping/21090_6.txt, time: 5.620000
/bbs/Gossiping/M.1495645979.A.331.html download to ptt/Gossiping/21090_7.txt, time: 4.770000
/bbs/Gossiping/M.1495645994.A.4EB.html download to ptt/Gossiping/21090_8.txt, time: 5.250000
/bbs/Gossiping/M.1495646044.A.AA1.html download to ptt/Gossiping/21090_9.txt, time: 9.070000
/bbs/Gossiping/M.1495646072.A.718.html download to ptt/Gossiping/21090_10.txt, time: 4.840000
/bbs/Gossiping/M.1495646127.A.BFD.html download to ptt/Gossiping/21090_11.txt, time: 4.020000
/bbs/Gossiping/M.1495646151.A.25C.html download to ptt/Gossiping/21090_12.txt, time: 4.370000
/bbs/Gossiping/M.1495646218.A.26C.html download to ptt/Gossiping/21090_13.txt, time: 7.290000
/bbs/Gossiping/M.1495646249.A.4A0.html download to ptt/Gossiping/21090_14.txt, time: 5.550000
/bbs/Gossiping/M.1495646265.A.FC2.html download to ptt/Gossiping/21090_15.txt, time: 7.000000
/bbs/Gossiping/M.1495646272.A.007.html download to ptt/Gossiping/21090_16.txt, time: 4.720000
/bbs/Gossiping/M.1495646273.A.4C5.html download to ptt/Gossiping/21090_17.txt, time: 4.880000
/bbs/Gossiping/M.1495646305.A.F8D.html download to ptt/Gossiping/21090_18.txt, time: 5.420000
/bbs/Gossiping/M.1495646313.A.606.html download to ptt/Gossiping/21090_19.txt, time: 4.340000
page 21089
/bbs/Gossiping/M.1495645028.A.3AA.html download to ptt/Gossiping/21089_0.txt, time: 5.220000
/bbs/Gossiping/M.1495645053.A.0F8.html download to ptt/Gossiping/21089_1.txt, time: 4.180000
/bbs/Gossiping/M.1495645066.A.8EB.html download to ptt/Gossiping/21089_2.txt, time: 5.770000
/bbs/Gossiping/M.1495645086.A.3F7.html download to ptt/Gossiping/21089_3.txt, time: 5.910000
/bbs/Gossiping/M.1495645086.A.B48.html download to ptt/Gossiping/21089_4.txt, time: 5.310000
/bbs/Gossiping/M.1495645088.A.E5A.html download to ptt/Gossiping/21089_5.txt, time: 4.670000
/bbs/Gossiping/M.1495645118.A.024.html download to ptt/Gossiping/21089_6.txt, time: 4.730000
/bbs/Gossiping/M.1495645153.A.116.html download to ptt/Gossiping/21089_7.txt, time: 4.740000
/bbs/Gossiping/M.1495645180.A.E3B.html download to ptt/Gossiping/21089_8.txt, time: 3.550000
/bbs/Gossiping/M.1495645255.A.888.html download to ptt/Gossiping/21089_9.txt, time: 4.150000
/bbs/Gossiping/M.1495645335.A.965.html download to ptt/Gossiping/21089_10.txt, time: 5.400000
/bbs/Gossiping/M.1495645393.A.E9E.html download to ptt/Gossiping/21089_11.txt, time: 4.210000
/bbs/Gossiping/M.1495645409.A.066.html download to ptt/Gossiping/21089_12.txt, time: 4.750000
/bbs/Gossiping/M.1495645415.A.5E3.html download to ptt/Gossiping/21089_13.txt, time: 4.060000
/bbs/Gossiping/M.1495645417.A.F9C.html download to ptt/Gossiping/21089_14.txt, time: 4.580000
/bbs/Gossiping/M.1495645430.A.7A9.html download to ptt/Gossiping/21089_15.txt, time: 4.320000
/bbs/Gossiping/M.1495645481.A.F41.html download to ptt/Gossiping/21089_16.txt, time: 6.870000
/bbs/Gossiping/M.1495645536.A.3E3.htmlTraceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/studentyl/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crawler.py", line 177, in <module>
    main(sys.argv[1:])
  File "./crawler.py", line 158, in main
    downloadForum(forumName, startPage, pages)
  File "./crawler.py", line 140, in downloadForum
    downloadPage(str(articleCount), forumName, pageNum, 'https://www.ptt.cc'+link)
  File "./crawler.py", line 82, in downloadPage
    pageText = getPageText(link)
  File "./crawler.py", line 13, in getPageText
    pageText=requests.get(link, cookies={'over18':'1'}).text
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/studentyl/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
